In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4,5])


In [6]:
np.savetxt('array_a',a  )


In [18]:
arr = np.loadtxt('read_this.txt',delimiter= ',', dtype = 'uint8')

ValueError: could not convert string to float: b'1;2;3;4;5;6 '

In [16]:
arr

array([1, 2, 3, 4, 5, 6], dtype=uint8)

In [20]:
arr*2


array([ 2,  4,  6,  8, 10, 12], dtype=uint8)

In [21]:
import os 

In [28]:
files = os.listdir()
files

['.ipynb_checkpoints',
 'array_a',
 'fibo_seq',
 'read_write_numpy.ipynb',
 'Untitled Folder']

In [29]:
files[3]

'read_write_numpy.ipynb'

In [47]:
file_loc = 'Untitled Folder/read_this.txt'

arr2 = np.loadtxt(file_loc, delimiter=',')

In [48]:
print(arr2)

[ 1.  2.  3.  4.  1.  2.  3.  4.]
